server:
  port: 8080
spring:
  application:
    name: "test-thread-pool"

xuegao:
  concurrent:
    # 开启为true，不开启则设置为false
    enable: true
    # 以下都有默认值，可以不设置
    # 线程池核心线程数
    corePoolSize: 16
    # 线程池最大线程数
    maximumPoolSize: 16
    # 超过核心线程数的线程的存活时间
    keepAliveTime: 30
    # 阻塞队列容量
    blockingQueueCapacity: 1024
    # 阻塞队列类型
    blockingQueueType: ARRAY_BLOCKING_QUEUE
    # 是否使用线程池并发执行查询
    concurrentActive: true
